### ISSUE TITLE
push flashbake on pypi

### ISSUE THREAD

**Issue by Psycojoker** [cmdln/flashbake#11]
Hello,

Can you push flashbake to pypi plz? Like that everyone will be able to install it using easy_install/pip.

Since you already have a working setup.py this should be very easy to do (2 commands to launch after creating an account on pypi: one to register to project, the other one to push it).

Thanks in advance,

Tell me if you'd like details instructions.

**Comment by brainwane** [comment]
The PyPI package: https://pypi.org/project/flashbake/
