### ISSUE TITLE
Rework entry point to be more easily re-used

### ISSUE THREAD

**Issue by cmdln** [cmdln/flashbake#2]
To start with, make it amenable to direct calling from the entry point used by the flashbakeall wrapper script.  Doing so should make the console module more useful for any other scripting purposes, like enhanced or alternate front ends.

**Comment by ianpaul** [comment]
So @cmdln  do you happen to remember with this issue...was the idea to make it easier to import flashbake into another script and then run `flashbakeall` from there?

**Comment by ianpaul** [comment]
Okay, let's close for now.
