### ISSUE TITLE
Idea: Plugin which puts last-modified dates of files with changes and similar data into the commit message

### ISSUE THREAD

**Issue by xtaran** [cmdln/flashbake#25]
What I mostly miss with flashbake is a plugin which puts the state of the repository into the commit message, especially those things I don't see by default in the commit, like e.g.
- File owners and groups
- Ignored, but present files
- Time stamps of (changed) files

All those things should be doable with an `ls -la` or so. Other, similar ideas, but maybe suitable for a different plugin:
- System's lastlog, i.e. show which users where last logged in when. Given a daily autocommit, probably the lastlog of the past 24 hours is the interesting one.

All those ideas gather around the need to have as much information as needed to figure out whose changes were automatically committed.

**Comment by ianpaul** [comment]
This issue is currently a work in progress and will be part of the next release. 
Anyone who's interested can check out the new plugins here: https://github.com/cmdln/flashbake/tree/repo_info_plugins
