### ISSUE TITLE
noreply.org no longer resolves

### ISSUE THREAD

**Issue by abhidg** [cmdln/flashbake#35]
Determination of location using noreply.org will fail as the domain no longer resolves:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919009

https://github.com/cmdln/flashbake/blob/434161f9c9ff765a2169af62adf2089582f884a1/src/flashbake/plugins/location.py#L144

**Comment by cmdln** [comment]
Looks like this could work though the parsing will have to be updated: http://www.iptools.com/

**Comment by abhidg** [comment]
https://api.ipify.org
https://ident.me

These return the IP in plain text.

**Comment by cmdln** [comment]
Even better.
