### ISSUE TITLE
Add more Python 3 styling

### ISSUE THREAD

**Issue by ianpaul** [cmdln/flashbake#42]
Although it still officially works, Python 3 styling uses `{}.format` for string formatting instead of `%s % variable`. This has been done in some places, but needs to be finished. If anyone else sees any other Python 3 styling changes that should happen please mention them in this thread.

**Comment by svenkat19** [comment]
Can you please assign this to me ? Thank you!

**Comment by ianpaul** [comment]
Great! Thank you for helping out. If you have any questions just hit me up or @cmdln
