### ISSUE TITLE
Add exception handling to plugins where appropriate

### ISSUE THREAD

**Issue by ianpaul** [cmdln/flashbake#43]
There are a number of plugins that connect to online resources and don't have exceptions built-in. That means when they fail, they fail hard with ugly error messages for the user. It would be better to avoid this when possible. See the `feed.py` plugin for an example of how error handling is typically employed.

**Comment by bumblebee211196** [comment]
Hey, I would like to work on this!.

**Comment by ianpaul** [comment]
Go for it @bumblebee211196 ! Please test that everything works before submitting a pull request. If something comes up and you have to stop working on this please contact me.

**Comment by bumblebee211196** [comment]
Sure!. Will notify you in case something important comes up!.

**Comment by bumblebee211196** [comment]
In order to run the test for `lastfm.py` plugin, I need the lastfm username. Do we have any usernames for testing? Or should I create a new one for myself?

**Comment by ianpaul** [comment]
> In order to run the test for `lastfm.py` plugin, I need the lastfm username. Do we have any usernames for testing? Or should I create a new one for myself?

Create one  yourself if that's ok.

**Comment by ianpaul** [comment]
Sorry @bumblebee211196 I just caught one tiny spelling mistake on line 53 of lastfm.py. `Coudlnt`, can you correct to `'Couldn\'t` with the escape character as written here, and submit a new pull request when you have a moment, please?

**Comment by bumblebee211196** [comment]
Yea sure. Will do it.
