### ISSUE TITLE
Add a contributor's guide

### ISSUE THREAD

**Issue by cmdln** [cmdln/flashbake#49]
As a potential contributor, having more documentation on how to make a first time contribution or many over time would be helpful and could encourage more people to help maintain flashbake.

Such a guide could include
* Coding conventions, formatting, and other suggested or required style
* How to run and test
* Expectations when submitting a PR such as best effort testing
* Common issues
* Guidance on our label usage

**Comment by cmdln** [comment]
@ianpaul assigning it to you because I think a good first pass could be using what you've written in comments as a start for this guide to contributors.

**Comment by ianpaul** [comment]
That sounds like a plan. I'll take care of it!

**Comment by ianpaul** [comment]
Okay, first pass is done, and ready for you to take a look.

https://github.com/cmdln/flashbake/wiki/Contributor's-Guide-(Draft)

**Comment by cmdln** [comment]
This looks great to me--:shipit:

**Comment by ianpaul** [comment]
awesome. So I'll take the "Draft" markings off it?

**Comment by cmdln** [comment]
Yes, please!
